import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./../globals.css";
import { ThemeInitializer } from "@/components/ThemeInitializer";
import { ToastContainer } from "react-toastify";
import { Header } from "@/components/Shared";
import { MainLayout } from "@/components/Shared/Layouts/Main";
import { Footer } from "@/components/Shared/Footer";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default async function RootLayout({ children }: RootLayoutProps) {
  const theme = (await cookies()).get("theme")?.value || "light";

  return (
    <html lang="pt-BR" className={theme === "dark" ? "dark" : ""} data-testid="root-layout">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeInitializer />
        <MainLayout>
          <Header />
          <ToastContainer />
            {children}
          <Footer />
        </MainLayout>
      </body>
    </html>
  );
}
