import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ThemeInitializer } from "@/components/ThemeInitializer";
import { ToastContainer } from "react-toastify";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  cookies?: string;
}

function getThemeFromCookie(cookie?: string): "light" | "dark" {
  if (!cookie) return "light";
  const match = cookie.match(/theme=(dark|light)/);
  return match ? (match[1] as "light" | "dark") : "light";
}

export default async function RootLayout({children,cookies}: RootLayoutProps) {
  const theme = getThemeFromCookie(cookies);
  const session = await getServerSession();

  const user = session?.user;
  if (!session) {
    redirect("/");
  }

  return (
    <html lang="pt-BR" className={theme === "dark" ? "dark" : ""} data-testid="root-layout-manage">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* <Header bg={"white"}>
                    <Logo />
                    <NavBar />
                </Header> */}
        <ThemeInitializer />
        <ToastContainer />
        {/* <LayoutManager>
                    <SideBar username={user?.name ?? "guest"} img={user?.image ?? "avatar.svg"} /> */}
        {/* <LoadContext> */}
        {children}
        {/* </LoadContext> */}
        {/* </LayoutManager> */}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
